# https://github.com/kentaro-m/auto-assign-action
name: "Auto Assign PR"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
