name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'source-repo'

      - name: Pushes to dev repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'source-repo/redirect'
          destination-github-username: 'ECUST-Leap'
          destination-repository-name: 'ecust-leap-dev'
          user-email: github-actions@github.com
          target-branch: main
