name: Lint Code Base

on:
  pull_request:
    branches: [dev, main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            docs/**/*.md
            blog/**/*.md