name: Test deployment

on:
  pull_request:
    branches:
      - main
      - dev
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test redirect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify redirect files
        run: |
          test -s redirect/index.html
          test -s redirect/404.html
          grep -q 'https://ecust-leap.pages.dev' redirect/index.html
          grep -q 'https://ecust-leap.pages.dev' redirect/404.html
